apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: simbay-cluster
spec:
  rayVersion: "2.55.1"
  headGroupSpec:
    serviceType: NodePort 
    rayStartParams:
      dashboard-host: "0.0.0.0"
      num-cpus: "0"
      num-gpus: "0"
    template:
      spec:
        containers:
          - name: ray-head
            image: marianascosta/simbay-ray:demo.2.55.1
            imagePullPolicy: IfNotPresent
            ports:
              - name: gcs
                containerPort: 6379
              - name: dashboard
                containerPort: 8265
              - name: client
                containerPort: 10001
            env:
              - name: PYTHONPATH
                value: /serve_app:/serve_app/src
              # - name: GRPC_ENABLE_FORK_SUPPORT
              #   value: "0"
              # - name: GRPC_POLL_STRATEGY
              #   value: "poll"
  workerGroupSpecs:
    - groupName: gpu-workers
      replicas: 1
      minReplicas: 1
      maxReplicas: 1
      rayStartParams:
        num-gpus: "1"
      template:
        spec:
          runtimeClassName: nvidia
          containers:
            - name: ray-worker
              image: marianascosta/simbay-ray:demo.2.55.1
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  nvidia.com/gpu: "1"
              env:
                - name: PYTHONPATH
                  value: /serve_app:/serve_app/src